use crate::bytecode::{Function, Instr, OpCode};
use crate::error::CompileError;

use super::util::{read_i64, read_str, read_u8, read_u32};

pub(super) fn read_function(buf: &[u8], cursor: &mut usize) -> Result<Function, CompileError> {
    let name = read_str(buf, cursor)?;
    let param_count = read_u32(buf, cursor)?;
    let locals = read_u32(buf, cursor)?;
    let code_len = read_u32(buf, cursor)? as usize;
    let mut code = Vec::with_capacity(code_len);
    for _ in 0..code_len {
        let instr = decode_instr(buf, cursor)?;
        code.push(instr);
    }
    Ok(Function {
        name,
        param_count,
        locals,
        code,
    })
}

fn decode_instr(buf: &[u8], cursor: &mut usize) -> Result<Instr, CompileError> {
    let op = read_u8(buf, cursor)?;
    let instr = match op {
        x if x == OpCode::ConstInt as u8 => Instr::ConstInt(read_i64(buf, cursor)?),
        x if x == OpCode::ConstBool as u8 => Instr::ConstBool(read_u8(buf, cursor)? != 0),
        x if x == OpCode::ConstStr as u8 => Instr::ConstStr(read_str(buf, cursor)?),
        x if x == OpCode::Load as u8 => Instr::Load(read_u32(buf, cursor)?),
        x if x == OpCode::Store as u8 => Instr::Store(read_u32(buf, cursor)?),
        x if x == OpCode::Add as u8 => Instr::Add,
        x if x == OpCode::Sub as u8 => Instr::Sub,
        x if x == OpCode::Mul as u8 => Instr::Mul,
        x if x == OpCode::Div as u8 => Instr::Div,
        x if x == OpCode::Eq as u8 => Instr::Eq,
        x if x == OpCode::Ne as u8 => Instr::Ne,
        x if x == OpCode::Lt as u8 => Instr::Lt,
        x if x == OpCode::Le as u8 => Instr::Le,
        x if x == OpCode::Gt as u8 => Instr::Gt,
        x if x == OpCode::Ge as u8 => Instr::Ge,
        x if x == OpCode::StrEq as u8 => Instr::StrEq,
        x if x == OpCode::StrNe as u8 => Instr::StrNe,
        x if x == OpCode::And as u8 => Instr::And,
        x if x == OpCode::Or as u8 => Instr::Or,
        x if x == OpCode::Not as u8 => Instr::Not,
        x if x == OpCode::Neg as u8 => Instr::Neg,
        x if x == OpCode::Jump as u8 => Instr::Jump(read_u32(buf, cursor)?),
        x if x == OpCode::JumpIfFalse as u8 => Instr::JumpIfFalse(read_u32(buf, cursor)?),
        x if x == OpCode::PrintLn as u8 => Instr::PrintLn,
        x if x == OpCode::ReadInt as u8 => Instr::ReadInt(read_u32(buf, cursor)?),
        x if x == OpCode::ReadBool as u8 => Instr::ReadBool(read_u32(buf, cursor)?),
        x if x == OpCode::ReadStr as u8 => Instr::ReadStr(read_u32(buf, cursor)?),
        x if x == OpCode::Call as u8 => Instr::Call(read_u32(buf, cursor)?),
        x if x == OpCode::Ret as u8 => Instr::Ret,
        x if x == OpCode::RetVal as u8 => Instr::RetVal,
        x if x == OpCode::AllocArray as u8 => Instr::AllocArray(read_u32(buf, cursor)?),
        x if x == OpCode::LoadIndex as u8 => Instr::LoadIndex,
        x if x == OpCode::StoreIndex as u8 => Instr::StoreIndex,
        x if x == OpCode::ReadFile as u8 => Instr::ReadFile,
        x if x == OpCode::WriteFile as u8 => Instr::WriteFile,
        x if x == OpCode::ArgCount as u8 => Instr::ArgCount,
        x if x == OpCode::Arg as u8 => Instr::Arg,
        x if x == OpCode::StrLen as u8 => Instr::StrLen,
        x if x == OpCode::StrConcat as u8 => Instr::StrConcat,
        x if x == OpCode::StrSubstr as u8 => Instr::StrSubstr,
        x if x == OpCode::StrReplace as u8 => Instr::StrReplace,
        x if x == OpCode::VecNew as u8 => Instr::VecNew,
        x if x == OpCode::VecLen as u8 => Instr::VecLen,
        x if x == OpCode::VecGet as u8 => Instr::VecGet,
        x if x == OpCode::VecSet as u8 => Instr::VecSet,
        x if x == OpCode::VecPush as u8 => Instr::VecPush,
        x if x == OpCode::VecRemove as u8 => Instr::VecRemove,
        x if x == OpCode::VecLast as u8 => Instr::VecLast,
        x if x == OpCode::VecPop as u8 => Instr::VecPop,
        x if x == OpCode::StackNew as u8 => Instr::StackNew,
        x if x == OpCode::StackLen as u8 => Instr::StackLen,
        x if x == OpCode::StackPush as u8 => Instr::StackPush,
        x if x == OpCode::StackTop as u8 => Instr::StackTop,
        x if x == OpCode::StackPop as u8 => Instr::StackPop,
        x if x == OpCode::MapNew as u8 => Instr::MapNew,
        x if x == OpCode::MapLen as u8 => Instr::MapLen,
        x if x == OpCode::MapSet as u8 => Instr::MapSet,
        x if x == OpCode::MapGet as u8 => Instr::MapGet,
        x if x == OpCode::MapHas as u8 => Instr::MapHas,
        x if x == OpCode::MapRemove as u8 => Instr::MapRemove,
        x if x == OpCode::SetNew as u8 => Instr::SetNew,
        x if x == OpCode::SetLen as u8 => Instr::SetLen,
        x if x == OpCode::SetAdd as u8 => Instr::SetAdd,
        x if x == OpCode::SetHas as u8 => Instr::SetHas,
        x if x == OpCode::SetRemove as u8 => Instr::SetRemove,
        x if x == OpCode::OptSomeInt as u8 => Instr::OptSomeInt,
        x if x == OpCode::OptSomeBool as u8 => Instr::OptSomeBool,
        x if x == OpCode::OptSomeStr as u8 => Instr::OptSomeStr,
        x if x == OpCode::OptNoneInt as u8 => Instr::OptNoneInt,
        x if x == OpCode::OptNoneBool as u8 => Instr::OptNoneBool,
        x if x == OpCode::OptNoneStr as u8 => Instr::OptNoneStr,
        x if x == OpCode::OptIsSomeInt as u8 => Instr::OptIsSomeInt,
        x if x == OpCode::OptIsSomeBool as u8 => Instr::OptIsSomeBool,
        x if x == OpCode::OptIsSomeStr as u8 => Instr::OptIsSomeStr,
        x if x == OpCode::OptUnwrapInt as u8 => Instr::OptUnwrapInt,
        x if x == OpCode::OptUnwrapBool as u8 => Instr::OptUnwrapBool,
        x if x == OpCode::OptUnwrapStr as u8 => Instr::OptUnwrapStr,
        x if x == OpCode::OptUnwrapOrInt as u8 => Instr::OptUnwrapOrInt,
        x if x == OpCode::OptUnwrapOrBool as u8 => Instr::OptUnwrapOrBool,
        x if x == OpCode::OptUnwrapOrStr as u8 => Instr::OptUnwrapOrStr,
        x if x == OpCode::ResOkInt as u8 => Instr::ResOkInt,
        x if x == OpCode::ResOkBool as u8 => Instr::ResOkBool,
        x if x == OpCode::ResOkStr as u8 => Instr::ResOkStr,
        x if x == OpCode::ResErrInt as u8 => Instr::ResErrInt,
        x if x == OpCode::ResErrBool as u8 => Instr::ResErrBool,
        x if x == OpCode::ResErrStr as u8 => Instr::ResErrStr,
        x if x == OpCode::ResIsOkInt as u8 => Instr::ResIsOkInt,
        x if x == OpCode::ResIsOkBool as u8 => Instr::ResIsOkBool,
        x if x == OpCode::ResIsOkStr as u8 => Instr::ResIsOkStr,
        x if x == OpCode::ResUnwrapInt as u8 => Instr::ResUnwrapInt,
        x if x == OpCode::ResUnwrapBool as u8 => Instr::ResUnwrapBool,
        x if x == OpCode::ResUnwrapStr as u8 => Instr::ResUnwrapStr,
        x if x == OpCode::ResUnwrapOrInt as u8 => Instr::ResUnwrapOrInt,
        x if x == OpCode::ResUnwrapOrBool as u8 => Instr::ResUnwrapOrBool,
        x if x == OpCode::ResUnwrapOrStr as u8 => Instr::ResUnwrapOrStr,
        x if x == OpCode::ResUnwrapErrInt as u8 => Instr::ResUnwrapErrInt,
        x if x == OpCode::ResUnwrapErrBool as u8 => Instr::ResUnwrapErrBool,
        x if x == OpCode::ResUnwrapErrStr as u8 => Instr::ResUnwrapErrStr,
        x if x == OpCode::StrClear as u8 => Instr::StrClear,
        x if x == OpCode::VecClear as u8 => Instr::VecClear,
        x if x == OpCode::StackClear as u8 => Instr::StackClear,
        x if x == OpCode::MapClear as u8 => Instr::MapClear,
        x if x == OpCode::SetClear as u8 => Instr::SetClear,
        x if x == OpCode::EnvGet as u8 => Instr::EnvGet,
        x if x == OpCode::EnvHas as u8 => Instr::EnvHas,
        x if x == OpCode::Cwd as u8 => Instr::Cwd,
        x if x == OpCode::PathJoin as u8 => Instr::PathJoin,
        x if x == OpCode::FsExists as u8 => Instr::FsExists,
        x if x == OpCode::FsListDir as u8 => Instr::FsListDir,
        x if x == OpCode::OsExec as u8 => Instr::OsExec,
        x if x == OpCode::NowTimestamp as u8 => Instr::NowTimestamp,
        x if x == OpCode::SleepMs as u8 => Instr::SleepMs,
        x if x == OpCode::LogStr as u8 => Instr::LogStr,
        x if x == OpCode::LogInt as u8 => Instr::LogInt,
        x if x == OpCode::LogBool as u8 => Instr::LogBool,
        x if x == OpCode::BcNew as u8 => Instr::BcNew,
        x if x == OpCode::BcMain as u8 => Instr::BcMain,
        x if x == OpCode::BcEmitPrintStr as u8 => Instr::BcEmitPrintStr,
        x if x == OpCode::BcEmitHalt as u8 => Instr::BcEmitHalt,
        x if x == OpCode::BcWrite as u8 => Instr::BcWrite,
        x if x == OpCode::BcEmitConstInt as u8 => Instr::BcEmitConstInt,
        x if x == OpCode::BcEmitStore0 as u8 => Instr::BcEmitStore0,
        x if x == OpCode::BcEmitLoad0 as u8 => Instr::BcEmitLoad0,
        x if x == OpCode::BcEmitPrintLn as u8 => Instr::BcEmitPrintLn,
        x if x == OpCode::BcEmitConstBool as u8 => Instr::BcEmitConstBool,
        x if x == OpCode::BcLabel as u8 => Instr::BcLabel,
        x if x == OpCode::BcJump as u8 => Instr::BcJump,
        x if x == OpCode::BcJumpIfFalse as u8 => Instr::BcJumpIfFalse,
        x if x == OpCode::BcEmitConstStr as u8 => Instr::BcEmitConstStr,
        x if x == OpCode::BcEmitLoad as u8 => Instr::BcEmitLoad,
        x if x == OpCode::BcEmitStore as u8 => Instr::BcEmitStore,
        x if x == OpCode::BcEmitAdd as u8 => Instr::BcEmitAdd,
        x if x == OpCode::BcEmitSub as u8 => Instr::BcEmitSub,
        x if x == OpCode::BcEmitMul as u8 => Instr::BcEmitMul,
        x if x == OpCode::BcEmitDiv as u8 => Instr::BcEmitDiv,
        x if x == OpCode::BcEmitEq as u8 => Instr::BcEmitEq,
        x if x == OpCode::BcEmitNe as u8 => Instr::BcEmitNe,
        x if x == OpCode::BcEmitLt as u8 => Instr::BcEmitLt,
        x if x == OpCode::BcEmitLe as u8 => Instr::BcEmitLe,
        x if x == OpCode::BcEmitGt as u8 => Instr::BcEmitGt,
        x if x == OpCode::BcEmitGe as u8 => Instr::BcEmitGe,
        x if x == OpCode::BcEmitAnd as u8 => Instr::BcEmitAnd,
        x if x == OpCode::BcEmitOr as u8 => Instr::BcEmitOr,
        x if x == OpCode::BcEmitNot as u8 => Instr::BcEmitNot,
        x if x == OpCode::BcEmitNeg as u8 => Instr::BcEmitNeg,
        x if x == OpCode::BcEmitStrLen as u8 => Instr::BcEmitStrLen,
        x if x == OpCode::BcEmitStrConcat as u8 => Instr::BcEmitStrConcat,
        x if x == OpCode::BcEmitStrSubstr as u8 => Instr::BcEmitStrSubstr,
        x if x == OpCode::BcEmitStrReplace as u8 => Instr::BcEmitStrReplace,
        x if x == OpCode::BcEmitVecNew as u8 => Instr::BcEmitVecNew,
        x if x == OpCode::BcEmitVecLen as u8 => Instr::BcEmitVecLen,
        x if x == OpCode::BcEmitVecGet as u8 => Instr::BcEmitVecGet,
        x if x == OpCode::BcEmitVecSet as u8 => Instr::BcEmitVecSet,
        x if x == OpCode::BcEmitVecPush as u8 => Instr::BcEmitVecPush,
        x if x == OpCode::BcEmitVecRemove as u8 => Instr::BcEmitVecRemove,
        x if x == OpCode::BcEmitVecLast as u8 => Instr::BcEmitVecLast,
        x if x == OpCode::BcEmitVecPop as u8 => Instr::BcEmitVecPop,
        x if x == OpCode::BcEmitMapNew as u8 => Instr::BcEmitMapNew,
        x if x == OpCode::BcEmitMapLen as u8 => Instr::BcEmitMapLen,
        x if x == OpCode::BcEmitMapSet as u8 => Instr::BcEmitMapSet,
        x if x == OpCode::BcEmitMapGet as u8 => Instr::BcEmitMapGet,
        x if x == OpCode::BcEmitMapHas as u8 => Instr::BcEmitMapHas,
        x if x == OpCode::BcEmitMapRemove as u8 => Instr::BcEmitMapRemove,
        x if x == OpCode::BcEmitReadFile as u8 => Instr::BcEmitReadFile,
        x if x == OpCode::BcEmitWriteFile as u8 => Instr::BcEmitWriteFile,
        x if x == OpCode::BcEmitArgCount as u8 => Instr::BcEmitArgCount,
        x if x == OpCode::BcEmitArg as u8 => Instr::BcEmitArg,
        x if x == OpCode::BcEmitStrClear as u8 => Instr::BcEmitStrClear,
        x if x == OpCode::BcEmitVecClear as u8 => Instr::BcEmitVecClear,
        x if x == OpCode::BcEmitMapClear as u8 => Instr::BcEmitMapClear,
        x if x == OpCode::BcFuncBegin as u8 => Instr::BcFuncBegin,
        x if x == OpCode::BcFuncEnd as u8 => Instr::BcFuncEnd,
        x if x == OpCode::BcEmitCall as u8 => Instr::BcEmitCall,
        x if x == OpCode::BcEmitRet as u8 => Instr::BcEmitRet,
        x if x == OpCode::BcEmitRetVal as u8 => Instr::BcEmitRetVal,
        x if x == OpCode::BcEmitEnvGet as u8 => Instr::BcEmitEnvGet,
        x if x == OpCode::BcEmitEnvHas as u8 => Instr::BcEmitEnvHas,
        x if x == OpCode::BcEmitCwd as u8 => Instr::BcEmitCwd,
        x if x == OpCode::BcEmitPathJoin as u8 => Instr::BcEmitPathJoin,
        x if x == OpCode::BcEmitFsExists as u8 => Instr::BcEmitFsExists,
        x if x == OpCode::BcEmitFsListDir as u8 => Instr::BcEmitFsListDir,
        x if x == OpCode::BcEmitNowTimestamp as u8 => Instr::BcEmitNowTimestamp,
        x if x == OpCode::BcEmitConstIntOp as u8 => Instr::BcEmitConstIntOp,
        x if x == OpCode::BcEmitConstBoolOp as u8 => Instr::BcEmitConstBoolOp,
        x if x == OpCode::BcEmitConstStrOp as u8 => Instr::BcEmitConstStrOp,
        x if x == OpCode::BcEmitLoadOp as u8 => Instr::BcEmitLoadOp,
        x if x == OpCode::BcEmitStoreOp as u8 => Instr::BcEmitStoreOp,
        x if x == OpCode::BcEmitCallOp as u8 => Instr::BcEmitCallOp,
        x if x == OpCode::BcNewOp as u8 => Instr::BcNewOp,
        x if x == OpCode::BcWriteOp as u8 => Instr::BcWriteOp,
        x if x == OpCode::BcLabelOp as u8 => Instr::BcLabelOp,
        x if x == OpCode::BcJumpOp as u8 => Instr::BcJumpOp,
        x if x == OpCode::BcJumpIfFalseOp as u8 => Instr::BcJumpIfFalseOp,
        x if x == OpCode::BcFuncBeginOp as u8 => Instr::BcFuncBeginOp,
        x if x == OpCode::BcMainOp as u8 => Instr::BcMainOp,
        x if x == OpCode::BcFuncEndOp as u8 => Instr::BcFuncEndOp,
        x if x == OpCode::BcEmitHaltOp as u8 => Instr::BcEmitHaltOp,
        x if x == OpCode::BcEmitRetOp as u8 => Instr::BcEmitRetOp,
        x if x == OpCode::BcEmitRetValOp as u8 => Instr::BcEmitRetValOp,
        x if x == OpCode::BcEmitPrintLnOp as u8 => Instr::BcEmitPrintLnOp,
        x if x == OpCode::BcEmitWriteFileOp as u8 => Instr::BcEmitWriteFileOp,
        x if x == OpCode::BcEmitAddOp as u8 => Instr::BcEmitAddOp,
        x if x == OpCode::BcEmitSubOp as u8 => Instr::BcEmitSubOp,
        x if x == OpCode::BcEmitMulOp as u8 => Instr::BcEmitMulOp,
        x if x == OpCode::BcEmitDivOp as u8 => Instr::BcEmitDivOp,
        x if x == OpCode::BcEmitEqOp as u8 => Instr::BcEmitEqOp,
        x if x == OpCode::BcEmitNeOp as u8 => Instr::BcEmitNeOp,
        x if x == OpCode::BcEmitLtOp as u8 => Instr::BcEmitLtOp,
        x if x == OpCode::BcEmitLeOp as u8 => Instr::BcEmitLeOp,
        x if x == OpCode::BcEmitGtOp as u8 => Instr::BcEmitGtOp,
        x if x == OpCode::BcEmitGeOp as u8 => Instr::BcEmitGeOp,
        x if x == OpCode::BcEmitAndOp as u8 => Instr::BcEmitAndOp,
        x if x == OpCode::BcEmitOrOp as u8 => Instr::BcEmitOrOp,
        x if x == OpCode::BcEmitNotOp as u8 => Instr::BcEmitNotOp,
        x if x == OpCode::BcEmitNegOp as u8 => Instr::BcEmitNegOp,
        x if x == OpCode::BcEmitStrLenOp as u8 => Instr::BcEmitStrLenOp,
        x if x == OpCode::BcEmitStrConcatOp as u8 => Instr::BcEmitStrConcatOp,
        x if x == OpCode::BcEmitStrSubstrOp as u8 => Instr::BcEmitStrSubstrOp,
        x if x == OpCode::BcEmitStrReplaceOp as u8 => Instr::BcEmitStrReplaceOp,
        x if x == OpCode::BcEmitVecNewOp as u8 => Instr::BcEmitVecNewOp,
        x if x == OpCode::BcEmitVecLenOp as u8 => Instr::BcEmitVecLenOp,
        x if x == OpCode::BcEmitVecGetOp as u8 => Instr::BcEmitVecGetOp,
        x if x == OpCode::BcEmitVecSetOp as u8 => Instr::BcEmitVecSetOp,
        x if x == OpCode::BcEmitVecPushOp as u8 => Instr::BcEmitVecPushOp,
        x if x == OpCode::BcEmitVecRemoveOp as u8 => Instr::BcEmitVecRemoveOp,
        x if x == OpCode::BcEmitVecLastOp as u8 => Instr::BcEmitVecLastOp,
        x if x == OpCode::BcEmitVecPopOp as u8 => Instr::BcEmitVecPopOp,
        x if x == OpCode::BcEmitVecClearOp as u8 => Instr::BcEmitVecClearOp,
        x if x == OpCode::BcEmitMapNewOp as u8 => Instr::BcEmitMapNewOp,
        x if x == OpCode::BcEmitMapLenOp as u8 => Instr::BcEmitMapLenOp,
        x if x == OpCode::BcEmitMapSetOp as u8 => Instr::BcEmitMapSetOp,
        x if x == OpCode::BcEmitMapGetOp as u8 => Instr::BcEmitMapGetOp,
        x if x == OpCode::BcEmitMapHasOp as u8 => Instr::BcEmitMapHasOp,
        x if x == OpCode::BcEmitMapRemoveOp as u8 => Instr::BcEmitMapRemoveOp,
        x if x == OpCode::BcEmitMapClearOp as u8 => Instr::BcEmitMapClearOp,
        x if x == OpCode::BcEmitReadFileOp as u8 => Instr::BcEmitReadFileOp,
        x if x == OpCode::BcEmitArgCountOp as u8 => Instr::BcEmitArgCountOp,
        x if x == OpCode::BcEmitArgOp as u8 => Instr::BcEmitArgOp,
        x if x == OpCode::BcEmitEnvGetOp as u8 => Instr::BcEmitEnvGetOp,
        x if x == OpCode::BcEmitEnvHasOp as u8 => Instr::BcEmitEnvHasOp,
        x if x == OpCode::BcEmitCwdOp as u8 => Instr::BcEmitCwdOp,
        x if x == OpCode::BcEmitPathJoinOp as u8 => Instr::BcEmitPathJoinOp,
        x if x == OpCode::BcEmitFsExistsOp as u8 => Instr::BcEmitFsExistsOp,
        x if x == OpCode::BcEmitFsListDirOp as u8 => Instr::BcEmitFsListDirOp,
        x if x == OpCode::BcEmitNowTimestampOp as u8 => Instr::BcEmitNowTimestampOp,
        x if x == OpCode::MetaBcNew as u8 => Instr::MetaBcNew,
        x if x == OpCode::MetaBcMain as u8 => Instr::MetaBcMain,
        x if x == OpCode::MetaBcWrite as u8 => Instr::MetaBcWrite,
        x if x == OpCode::MetaBcFuncBegin as u8 => Instr::MetaBcFuncBegin,
        x if x == OpCode::MetaBcFuncEnd as u8 => Instr::MetaBcFuncEnd,
        x if x == OpCode::MetaBcEmitHalt as u8 => Instr::MetaBcEmitHalt,
        x if x == OpCode::MetaBcLabel as u8 => Instr::MetaBcLabel,
        x if x == OpCode::MetaBcJump as u8 => Instr::MetaBcJump,
        x if x == OpCode::MetaBcJumpIfFalse as u8 => Instr::MetaBcJumpIfFalse,
        x if x == OpCode::Halt as u8 => Instr::Halt,
        _ => return Err(CompileError::new_simple("invalid opcode")),
    };
    Ok(instr)
}
