use crate::lexer::token::TokenKind;

pub fn keyword_kind(ident: &str) -> TokenKind {
    match ident {
        "program" => TokenKind::Program,
        "var" => TokenKind::Var,
        "begin" => TokenKind::Begin,
        "end" => TokenKind::End,
        "if" => TokenKind::If,
        "then" => TokenKind::Then,
        "else" => TokenKind::Else,
        "while" => TokenKind::While,
        "do" => TokenKind::Do,
        "procedure" => TokenKind::Procedure,
        "function" => TokenKind::Function,
        "return" => TokenKind::Return,
        "uses" => TokenKind::Uses,
        "array" => TokenKind::Array,
        "of" => TokenKind::Of,
        "integer" => TokenKind::Integer,
        "boolean" => TokenKind::Boolean,
        "string" => TokenKind::String,
        "option" => TokenKind::Option,
        "result" => TokenKind::Result,
        "vector" => TokenKind::Vector,
        "list" => TokenKind::List,
        "stack" => TokenKind::Stack,
        "map" => TokenKind::Map,
        "set" => TokenKind::Set,
        "true" => TokenKind::True,
        "false" => TokenKind::False,
        "writeln" => TokenKind::Writeln,
        "readln" => TokenKind::Readln,
        "and" => TokenKind::And,
        "or" => TokenKind::Or,
        "not" => TokenKind::Not,
        _ => TokenKind::Ident(ident.to_string()),
    }
}
