#[derive(Debug, Clone, Copy)]
#[repr(u8)]
pub enum OpCode {
    ConstInt = 1,
    ConstBool = 2,
    ConstStr = 3,
    Load = 4,
    Store = 5,
    Add = 6,
    Sub = 7,
    Mul = 8,
    Div = 9,
    Eq = 10,
    Ne = 11,
    Lt = 12,
    Le = 13,
    Gt = 14,
    Ge = 15,
    StrEq = 16,
    StrNe = 17,
    And = 18,
    Or = 19,
    Not = 20,
    Neg = 21,
    Jump = 22,
    JumpIfFalse = 23,
    PrintLn = 24,
    ReadInt = 25,
    ReadBool = 26,
    ReadStr = 27,
    Call = 28,
    Ret = 29,
    RetVal = 30,
    AllocArray = 31,
    LoadIndex = 32,
    StoreIndex = 33,
    ReadFile = 34,
    WriteFile = 35,
    ArgCount = 36,
    Arg = 37,
    StrLen = 38,
    StrConcat = 39,
    StrSubstr = 40,
    StrReplace = 41,
    VecNew = 42,
    VecLen = 43,
    VecGet = 44,
    VecSet = 45,
    VecPush = 46,
    VecRemove = 47,
    VecLast = 48,
    VecPop = 49,
    StackNew = 50,
    StackLen = 51,
    StackPush = 52,
    StackTop = 53,
    StackPop = 54,
    MapNew = 55,
    MapLen = 56,
    MapSet = 57,
    MapGet = 58,
    MapHas = 59,
    MapRemove = 60,
    SetNew = 61,
    SetLen = 62,
    SetAdd = 63,
    SetHas = 64,
    SetRemove = 65,
    OptSomeInt = 66,
    OptSomeBool = 67,
    OptSomeStr = 68,
    OptNoneInt = 69,
    OptNoneBool = 70,
    OptNoneStr = 71,
    OptIsSomeInt = 72,
    OptIsSomeBool = 73,
    OptIsSomeStr = 74,
    OptUnwrapInt = 75,
    OptUnwrapBool = 76,
    OptUnwrapStr = 77,
    OptUnwrapOrInt = 78,
    OptUnwrapOrBool = 79,
    OptUnwrapOrStr = 80,
    ResOkInt = 81,
    ResOkBool = 82,
    ResOkStr = 83,
    ResErrInt = 84,
    ResErrBool = 85,
    ResErrStr = 86,
    ResIsOkInt = 87,
    ResIsOkBool = 88,
    ResIsOkStr = 89,
    ResUnwrapInt = 90,
    ResUnwrapBool = 91,
    ResUnwrapStr = 92,
    ResUnwrapOrInt = 93,
    ResUnwrapOrBool = 94,
    ResUnwrapOrStr = 95,
    ResUnwrapErrInt = 96,
    ResUnwrapErrBool = 97,
    ResUnwrapErrStr = 98,
    StrClear = 99,
    VecClear = 100,
    StackClear = 101,
    MapClear = 102,
    SetClear = 103,
    EnvGet = 104,
    EnvHas = 105,
    Cwd = 106,
    PathJoin = 107,
    FsExists = 108,
    FsListDir = 109,
    NowTimestamp = 110,
    SleepMs = 111,
    LogStr = 112,
    LogInt = 113,
    LogBool = 114,
    BcNew = 115,
    BcMain = 116,
    BcEmitPrintStr = 117,
    BcEmitHalt = 118,
    BcWrite = 119,
    BcEmitConstInt = 120,
    BcEmitStore0 = 121,
    BcEmitLoad0 = 122,
    BcEmitPrintLn = 123,
    BcEmitConstBool = 124,
    BcLabel = 125,
    BcJump = 126,
    BcJumpIfFalse = 127,
    BcEmitConstStr = 128,
    BcEmitLoad = 129,
    BcEmitStore = 130,
    BcEmitAdd = 131,
    BcEmitSub = 132,
    BcEmitMul = 133,
    BcEmitDiv = 134,
    BcEmitEq = 135,
    BcEmitNe = 136,
    BcEmitLt = 137,
    BcEmitLe = 138,
    BcEmitGt = 139,
    BcEmitGe = 140,
    BcEmitAnd = 141,
    BcEmitOr = 142,
    BcEmitNot = 143,
    BcEmitNeg = 144,
    BcEmitStrLen = 145,
    BcEmitStrConcat = 146,
    BcEmitStrSubstr = 147,
    BcEmitStrReplace = 148,
    BcEmitVecNew = 149,
    BcEmitVecLen = 150,
    BcEmitVecGet = 151,
    BcEmitVecSet = 152,
    BcEmitVecPush = 153,
    BcEmitVecRemove = 154,
    BcEmitVecLast = 155,
    BcEmitVecPop = 156,
    BcEmitMapNew = 157,
    BcEmitMapLen = 158,
    BcEmitMapSet = 159,
    BcEmitMapGet = 160,
    BcEmitMapHas = 161,
    BcEmitMapRemove = 162,
    BcEmitReadFile = 163,
    BcEmitWriteFile = 164,
    BcEmitArgCount = 165,
    BcEmitArg = 166,
    BcEmitStrClear = 167,
    BcEmitVecClear = 168,
    BcEmitMapClear = 169,
    BcFuncBegin = 170,
    BcFuncEnd = 171,
    BcEmitCall = 172,
    BcEmitRet = 173,
    BcEmitRetVal = 174,
    BcEmitEnvGet = 175,
    BcEmitEnvHas = 176,
    BcEmitCwd = 177,
    BcEmitPathJoin = 178,
    BcEmitFsExists = 179,
    BcEmitFsListDir = 180,
    BcEmitNowTimestamp = 181,
    BcEmitConstIntOp = 182,
    BcEmitConstBoolOp = 183,
    BcEmitConstStrOp = 184,
    BcEmitLoadOp = 185,
    BcEmitStoreOp = 186,
    BcEmitCallOp = 187,
    BcNewOp = 188,
    BcWriteOp = 189,
    BcLabelOp = 190,
    BcJumpOp = 191,
    BcJumpIfFalseOp = 192,
    BcFuncBeginOp = 193,
    BcMainOp = 194,
    BcFuncEndOp = 195,
    BcEmitHaltOp = 196,
    BcEmitRetOp = 197,
    BcEmitRetValOp = 198,
    BcEmitPrintLnOp = 199,
    BcEmitWriteFileOp = 200,
    BcEmitAddOp = 201,
    BcEmitSubOp = 202,
    BcEmitMulOp = 203,
    BcEmitDivOp = 204,
    BcEmitEqOp = 205,
    BcEmitNeOp = 206,
    BcEmitLtOp = 207,
    BcEmitLeOp = 208,
    BcEmitGtOp = 209,
    BcEmitGeOp = 210,
    BcEmitAndOp = 211,
    BcEmitOrOp = 212,
    BcEmitNotOp = 213,
    BcEmitNegOp = 214,
    BcEmitStrLenOp = 215,
    BcEmitStrConcatOp = 216,
    BcEmitStrSubstrOp = 217,
    BcEmitStrReplaceOp = 218,
    BcEmitVecNewOp = 219,
    BcEmitVecLenOp = 220,
    BcEmitVecGetOp = 221,
    BcEmitVecSetOp = 222,
    BcEmitVecPushOp = 223,
    BcEmitVecRemoveOp = 224,
    BcEmitVecLastOp = 225,
    BcEmitVecPopOp = 226,
    BcEmitVecClearOp = 227,
    BcEmitMapNewOp = 228,
    BcEmitMapLenOp = 229,
    BcEmitMapSetOp = 230,
    BcEmitMapGetOp = 231,
    BcEmitMapHasOp = 232,
    BcEmitMapRemoveOp = 233,
    BcEmitMapClearOp = 234,
    BcEmitReadFileOp = 235,
    BcEmitArgCountOp = 236,
    BcEmitArgOp = 237,
    BcEmitEnvGetOp = 238,
    BcEmitEnvHasOp = 239,
    BcEmitCwdOp = 240,
    BcEmitPathJoinOp = 241,
    BcEmitFsExistsOp = 242,
    BcEmitFsListDirOp = 243,
    BcEmitNowTimestampOp = 244,
    MetaBcNew = 245,
    MetaBcMain = 246,
    MetaBcWrite = 247,
    MetaBcFuncBegin = 248,
    MetaBcFuncEnd = 249,
    MetaBcEmitHalt = 250,
    MetaBcLabel = 251,
    MetaBcJump = 252,
    MetaBcJumpIfFalse = 253,
    Halt = 255,
}

#[derive(Debug, Clone)]
pub enum Instr {
    ConstInt(i64),
    ConstBool(bool),
    ConstStr(String),
    Load(u32),
    Store(u32),
    Add,
    Sub,
    Mul,
    Div,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    StrEq,
    StrNe,
    And,
    Or,
    Not,
    Neg,
    Jump(u32),
    JumpIfFalse(u32),
    PrintLn,
    ReadInt(u32),
    ReadBool(u32),
    ReadStr(u32),
    Call(u32),
    Ret,
    RetVal,
    AllocArray(u32),
    LoadIndex,
    StoreIndex,
    ReadFile,
    WriteFile,
    ArgCount,
    Arg,
    StrLen,
    StrConcat,
    StrSubstr,
    StrReplace,
    VecNew,
    VecLen,
    VecGet,
    VecSet,
    VecPush,
    VecRemove,
    VecLast,
    VecPop,
    StackNew,
    StackLen,
    StackPush,
    StackTop,
    StackPop,
    MapNew,
    MapLen,
    MapSet,
    MapGet,
    MapHas,
    MapRemove,
    SetNew,
    SetLen,
    SetAdd,
    SetHas,
    SetRemove,
    OptSomeInt,
    OptSomeBool,
    OptSomeStr,
    OptNoneInt,
    OptNoneBool,
    OptNoneStr,
    OptIsSomeInt,
    OptIsSomeBool,
    OptIsSomeStr,
    OptUnwrapInt,
    OptUnwrapBool,
    OptUnwrapStr,
    OptUnwrapOrInt,
    OptUnwrapOrBool,
    OptUnwrapOrStr,
    ResOkInt,
    ResOkBool,
    ResOkStr,
    ResErrInt,
    ResErrBool,
    ResErrStr,
    ResIsOkInt,
    ResIsOkBool,
    ResIsOkStr,
    ResUnwrapInt,
    ResUnwrapBool,
    ResUnwrapStr,
    ResUnwrapOrInt,
    ResUnwrapOrBool,
    ResUnwrapOrStr,
    ResUnwrapErrInt,
    ResUnwrapErrBool,
    ResUnwrapErrStr,
    StrClear,
    VecClear,
    StackClear,
    MapClear,
    SetClear,
    EnvGet,
    EnvHas,
    Cwd,
    PathJoin,
    FsExists,
    FsListDir,
    NowTimestamp,
    SleepMs,
    LogStr,
    LogInt,
    LogBool,
    BcNew,
    BcMain,
    BcEmitPrintStr,
    BcEmitHalt,
    BcWrite,
    BcEmitConstInt,
    BcEmitStore0,
    BcEmitLoad0,
    BcEmitPrintLn,
    BcEmitConstBool,
    BcLabel,
    BcJump,
    BcJumpIfFalse,
    BcEmitConstStr,
    BcEmitLoad,
    BcEmitStore,
    BcEmitAdd,
    BcEmitSub,
    BcEmitMul,
    BcEmitDiv,
    BcEmitEq,
    BcEmitNe,
    BcEmitLt,
    BcEmitLe,
    BcEmitGt,
    BcEmitGe,
    BcEmitAnd,
    BcEmitOr,
    BcEmitNot,
    BcEmitNeg,
    BcEmitStrLen,
    BcEmitStrConcat,
    BcEmitStrSubstr,
    BcEmitStrReplace,
    BcEmitVecNew,
    BcEmitVecLen,
    BcEmitVecGet,
    BcEmitVecSet,
    BcEmitVecPush,
    BcEmitVecRemove,
    BcEmitVecLast,
    BcEmitVecPop,
    BcEmitMapNew,
    BcEmitMapLen,
    BcEmitMapSet,
    BcEmitMapGet,
    BcEmitMapHas,
    BcEmitMapRemove,
    BcEmitReadFile,
    BcEmitWriteFile,
    BcEmitArgCount,
    BcEmitArg,
    BcEmitStrClear,
    BcEmitVecClear,
    BcEmitMapClear,
    BcFuncBegin,
    BcFuncEnd,
    BcEmitCall,
    BcEmitRet,
    BcEmitRetVal,
    BcEmitEnvGet,
    BcEmitEnvHas,
    BcEmitCwd,
    BcEmitPathJoin,
    BcEmitFsExists,
    BcEmitFsListDir,
    BcEmitNowTimestamp,
    BcEmitConstIntOp,
    BcEmitConstBoolOp,
    BcEmitConstStrOp,
    BcEmitLoadOp,
    BcEmitStoreOp,
    BcEmitCallOp,
    BcNewOp,
    BcWriteOp,
    BcLabelOp,
    BcJumpOp,
    BcJumpIfFalseOp,
    BcFuncBeginOp,
    BcMainOp,
    BcFuncEndOp,
    BcEmitHaltOp,
    BcEmitRetOp,
    BcEmitRetValOp,
    BcEmitPrintLnOp,
    BcEmitWriteFileOp,
    BcEmitAddOp,
    BcEmitSubOp,
    BcEmitMulOp,
    BcEmitDivOp,
    BcEmitEqOp,
    BcEmitNeOp,
    BcEmitLtOp,
    BcEmitLeOp,
    BcEmitGtOp,
    BcEmitGeOp,
    BcEmitAndOp,
    BcEmitOrOp,
    BcEmitNotOp,
    BcEmitNegOp,
    BcEmitStrLenOp,
    BcEmitStrConcatOp,
    BcEmitStrSubstrOp,
    BcEmitStrReplaceOp,
    BcEmitVecNewOp,
    BcEmitVecLenOp,
    BcEmitVecGetOp,
    BcEmitVecSetOp,
    BcEmitVecPushOp,
    BcEmitVecRemoveOp,
    BcEmitVecLastOp,
    BcEmitVecPopOp,
    BcEmitVecClearOp,
    BcEmitMapNewOp,
    BcEmitMapLenOp,
    BcEmitMapSetOp,
    BcEmitMapGetOp,
    BcEmitMapHasOp,
    BcEmitMapRemoveOp,
    BcEmitMapClearOp,
    BcEmitReadFileOp,
    BcEmitArgCountOp,
    BcEmitArgOp,
    BcEmitEnvGetOp,
    BcEmitEnvHasOp,
    BcEmitCwdOp,
    BcEmitPathJoinOp,
    BcEmitFsExistsOp,
    BcEmitFsListDirOp,
    BcEmitNowTimestampOp,
    MetaBcNew,
    MetaBcMain,
    MetaBcWrite,
    MetaBcFuncBegin,
    MetaBcFuncEnd,
    MetaBcEmitHalt,
    MetaBcLabel,
    MetaBcJump,
    MetaBcJumpIfFalse,
    Halt,
}

#[derive(Debug, Clone)]
pub struct Bytecode {
    pub name: String,
    pub functions: Vec<Function>,
    pub entry: u32,
}

#[derive(Debug, Clone)]
pub struct Function {
    pub name: String,
    pub param_count: u32,
    pub locals: u32,
    pub code: Vec<Instr>,
}
